name: bartoo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.7.0 <4.0.0"

scripts:
  web: flutter run -d c --web-renderer canvaskit --web-port=50000

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  core:
    path: ../../packages/core
  ui:
    path: ../../packages/ui
  base:
    path: ../../packages/base
  utils:
    path: ../../packages/utils

  flutter_dotenv: ^5.0.2
  flutter_map: ^8.1.1
  flutter_svg: ^2.0.10+1
  dynamic_path_url_strategy: ^1.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.10
  image_picker: ^1.1.2
  indexed: ^0.0.8
  infinite_scroll_pagination: ^5.0.0
  intersperse: ^2.0.0
  intl: ^0.20.2
  introduction_screen: ^3.1.8
  json_annotation: ^4.6.0
  json_model: ^1.0.0
  json_serializable: ^6.3.1
  json_theme: 8.0.0+2
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.0
  logger: ^2.4.0
  moment_dart: ^5.0.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  uuid: ^4.5.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - ../../.env
    - assets/images/
    - assets/map_styles/dark_map_style.txt
    - assets/map_styles/light_map_style.txt

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/K2D/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D/K2D-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_24pt-Bold.ttf
          weight: 700
